### ISSUE TITLE
Occasional Garbled text

### ISSUE THREAD

**Issue by timshannon** [fmoralesc/neovim-gnome-terminal-wrapper#10]
Sometimes when I save a file, or resize a window I see some garbled text on the screen.  Usually a screen resize will clear it.

Not sure if it's an upstream issue or not, or even if there's anything you can do, but I've only seen it using the gnome-terminal wrapper, and not in a terminal on it's own, so I figured I'd open an issue.

![garbled](https://cloud.githubusercontent.com/assets/1330485/11801134/900effde-a2a8-11e5-948f-3ef52914563d.png)

thanks,

**Comment by fmoralesc** [comment]
Hm... If that only happens in the wrapper, perhaps some environment variable is not being set properly for some reason. Check `$TERM`.

**Comment by timshannon** [comment]
The results of opening up a new terminal from within the wrapper running `echo $TERM` 

`xterm-256color`

**Comment by wasowski** [comment]
I have noticed the same problems when I enabled changes of cursor shapes in my neovim just in regular invocation inside gnome-terminal.  I think these issues are related.  The string "tmux" quite often appears in the garbled text. Perhaps this rings a bell to someone?

My `echo $TERM` also gives `xterm-256color`

**Comment by fmoralesc** [comment]
This issue is also being discussed in https://github.com/neovim/neovim/issues/3875, as referenced in https://github.com/neovim/neovim/issues/4110.

**Comment by fmoralesc** [comment]
I will assume this was fixed already, closing.
