### ISSUE TITLE
Open wrapper in current dir, not home dir

### ISSUE THREAD

**Issue by thriveth** [fmoralesc/neovim-gnome-terminal-wrapper#11]
Thank you for creating this wrapper! It is really neat and has replaced gVim in my daily work.
One minor thing bugs me, though - when I have my terminal open in a project dir and want to open a file in that dir, I would usually just type `vim filename.py` and it would pop open. Now when I use nvim-wrapper, it always opens in my home dir, so in order to open a file in my current working dir, I have to `nvim-wrapper ~/path/to/dir/filename.py`, which is a quite a few extra keystrokes.

Is there a way to make the wrapper aware of current working dir when called from the command line?

**Comment by fmoralesc** [comment]
Sorry for the late response, life has been busy this past month ;)

Hm... I don't have this issue, but it might be because I use this https://github.com/fmoralesc/vim-extended-autochdir Can you try it? Otherwise I'll see if I can make it work without it.

**Comment by fmoralesc** [comment]
Another option is using an alias. This should work:

```
alias nvim=nvim-wrapper -c 'exe "lcd" . getcwd()'
```

**Comment by fmoralesc** [comment]
Ok, I finally got it done, it should work like this by default now.
