### ISSUE TITLE
wrong $PATH

### ISSUE THREAD

**Issue by punknroll** [fmoralesc/neovim-gnome-terminal-wrapper#12]
Hi,

my custom $PATH from .bashrc is not recognised by the wrapper. How can I do that?

Thanx

**Comment by fmoralesc** [comment]
Since I don't use vim remotely, I change $PATH directly in my vimrc. 

You can also do something like this:

``` vim
if systemlist('pathname')[0] == "my-host"
    let $PATH=$HOME."/bin/:" .$HOME."/.cabal/bin/:" .$PATH
endif
```

**Comment by punknroll** [comment]
Thanks that worked well!
