### ISSUE TITLE
neovim airline fonts

### ISSUE THREAD

**Issue by StefanYohansson** [fmoralesc/neovim-gnome-terminal-wrapper#13]
Hi guys,

I was configuring my nvim init and when I open using gnome-terminal by "nvim" command everything looks good. But when I run wrapper airline fonts crash.

![screenshot from 2016-03-16 15-03-07](https://cloud.githubusercontent.com/assets/1783252/13823591/0f9acad4-eb89-11e5-8a45-f62165d34f4c.png)

**Comment by fmoralesc** [comment]
The wrapper is probably using a different profile for some reason, try configuring it independently.

**Comment by StefanYohansson** [comment]
Hey @fmoralesc , thanks for the fast feedback.
Unfortunately no. I tried this. (screenshot attached) Another tip? I'm out of ideas.

![screenshot from 2016-03-16 15-32-41](https://cloud.githubusercontent.com/assets/1783252/13824381/87848172-eb8c-11e5-980a-7edb9d8904c1.png)

**Comment by fmoralesc** [comment]
Weird. The only things the wrapper sets that the regular terminal might not are the environment variables, `NVIM_TUI_ENABLE_CURSOR_SHAPE` and `NVIM_TUI_ENABLE_TRUE_COLOR`. What happens when, in the regular terminal, you set those before launching vim?

**Comment by StefanYohansson** [comment]
ha! You find it. When I set this `NVIM_TUI_ENABLE_TRUE_COLOR` flag, bug reveals itself.

**Comment by fmoralesc** [comment]
Hm... it seems like a conflict with powerline/airline and nvim, I'm not sure how to handle that. The variable should be benign. I found https://github.com/vim-airline/vim-airline/issues/916 and https://github.com/vim-airline/vim-airline/issues/840 but no resolution of the issue other than trying another font :/

**Comment by StefanYohansson** [comment]
Thanks @fmoralesc.

From now, I just updated my `.desktop` file to `Exec=env NVIM_TUI_ENABLE_TRUE_COLOR= nvim-wrapper %F`.

**Comment by fmoralesc** [comment]
Cool. I'll keep the issue open just in case.
