### ISSUE TITLE
Colorscheme broken in gnome-terminal 3.20

### ISSUE THREAD

**Issue by Soulou** [fmoralesc/neovim-gnome-terminal-wrapper#17]
After upgrading to GNOME Terminal 3.20.2, when I start neovim, I fallback on a dirty 256 colors 
![screenshot from 2016-08-29 14-53-38](https://cloud.githubusercontent.com/assets/329969/18052051/82e02fd8-6df8-11e6-9421-ca4302cafa27.png)

Here is the same colorscheme with gvim:
![screenshot from 2016-08-29 14-54-58](https://cloud.githubusercontent.com/assets/329969/18052089/b751e810-6df8-11e6-9ebb-ab38c8abd568.png)

As stated previously, colors were working before last upgrade. Any idea?

Thanks

**Comment by fmoralesc** [comment]
I think this is due to https://github.com/neovim/neovim/wiki/Following-HEAD#20160511 

We might need to set this automatically.

**Comment by fmoralesc** [comment]
Should be fixed in 2b39dffb095315fe9780bc0c71e64946ae197699

**Comment by ysolis** [comment]
I am not if is related but i have the same problem, the only difference is that i use gnome-terminal 3.18, in my case i lost the transparency mode with neovim-gnome-terminal-wrapper that i already have setup in gnome-terminal. If i minimize my window and maximize again, you can see this [here](http://screencloud.net/v/1jY0)

**Comment by fmoralesc** [comment]
That looks like a different issue. How do you set the transparency?

**Comment by ysolis** [comment]
transperency from gnome-terminal 3.18 settings. I now see that 3.20 drop support for transparency in profile settings, you need patches versions for fedora and archlinux for example (i don't know if Ubuntu will patch gnome-terminal in next versions, in Ubuntu 16.04 we use gnome-terminal 3.18)

I correct my problem @fmoralesc related to my version, recently updated to neovim 0.1.5 and changes in my ~/.config/nvim/init.vim needed for me. I will upload my config later (i use gitlab for this ...)

**Comment by fmoralesc** [comment]
Is this still an issue?

**Comment by ysolis** [comment]
not for me ... gnome-terminal 3.18 and neovim 0.1.7 under Ubuntu 16.04.1 works well :)
