### ISSUE TITLE
Gtk-WARNING when resizing window

### ISSUE THREAD

**Issue by akosladanyi** [fmoralesc/neovim-gnome-terminal-wrapper#18]
Gtk-WARNING **: Allocating size to GtkScrollbar 0x562ddb88d1f0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

I get the above warning whenever I resize the nvim-wrapper window.  GNOME terminal version: 3.20.2.

**Comment by fmoralesc** [comment]
The wrapper doesn't render anything itself, this was coming from the terminal itself. Closing because there is nothing to do.
