### ISSUE TITLE
Not compatible with Zsh

### ISSUE THREAD

**Issue by mraxilus** [fmoralesc/neovim-gnome-terminal-wrapper#19]
When starting up the nvim wrapper neovim is unable to find a few binaries I exported to $PATH in my zshrc. This mostly includes packages I manually installed in /opt. I can get around the issue by manually updating the $PATH environment variable in the nvim-wrapper python file. For obvious reasons, this is less than ideal as I would have to update this everytime I modify/add a new package manually. Is there some way to auto import the $PATH defined in .zshrc as I assume this works for bash users?

**Comment by fmoralesc** [comment]
It has nothing to do with the shell, see http://unix.stackexchange.com/questions/23637/gvim-uses-a-different-path-than-my-system. Same issue.

**Comment by mraxilus** [comment]
I see. I will just put my PATH modifications in .profile from now on. Thanks.
