### ISSUE TITLE
Setup for Ubuntu based distros?

### ISSUE THREAD

**Issue by danihodovic** [fmoralesc/neovim-gnome-terminal-wrapper#2]
I'm currently running Lubuntu and although I haven't tried setting this up for my system, I was wondering if it would be different than the manual way described in the README.md?

**Comment by fmoralesc** [comment]
It should be the same, you just need to move nvim-wrapper somewhere in your path (`~/bin/` works) and adjust the desktop file (`~/.local/share/applications/`) and icon accordingly.

**Comment by danihodovic** [comment]
Thanks

**Comment by mrehayden1** [comment]
> It should be the same, you just need to move nvim-wrapper somewhere in your path (`~/bin/` works) and adjust the desktop file (`~/.local/share/applications/`) and icon accordingly.

Just to add, it has to be `~/bin` in a fresh install if you're installing this script per user since `~/.local/bin` will not be in the desktop environment's PATH. This had me scratching my head for a while.
