### ISSUE TITLE
Issue Loading Environment Variables

### ISSUE THREAD

**Issue by Grogglex** [fmoralesc/neovim-gnome-terminal-wrapper#21]
I'm using NPM packages for some of my plugins (tern, coffeescript, coffeeline, etc). Normally the their path is loaded by my .bashrc but when I start Neovim I'm noticing that none of these are available. Is there a straight-forward way to get it to read in my exports?

**Comment by fmoralesc** [comment]
There's two options:
1) You can add the paths to PATH in the init.vim file,
2) You can modify the wrapper like we do [here](https://github.com/fmoralesc/neovim-gnome-terminal-wrapper/blob/master/nvim-wrapper#L95-L99).

When called from a shell, the wrapper should copy the environment, so in those cases it should work-as-is.

**Comment by Grogglex** [comment]
Thanks @fmoralesc that solved my problem.
