### ISSUE TITLE
Colorscheme not being set properly

### ISSUE THREAD

**Issue by addisonamiri** [fmoralesc/neovim-gnome-terminal-wrapper#3]
I'm having a weird bug where the colorscheme isn't getting set correctly. It works when I launch neovim myself from a gnome-terminal and if I do `:colorscheme solarized` it fixes it but it looks like the default theme. Even the internal variable is set at `solarized` so I'm not sure what's happening. Can you think of anything? I looked through the script but I can't see anything apparent that'll cause it. Is it happening on your end too?

**Comment by fmoralesc** [comment]
Since this sets the NVIM_TUI_ENABLE_TRUE_COLOR environment variable, it might be messing up with your particular colorscheme. Try removing it from the .desktop file, so it reads:

```
...
Exec=nvim-wrapper %F
...
```

**Comment by addisonamiri** [comment]
That fixed it. Now I need to figure out why gnome-terminal isn't supporting true color... Thanks :)

**Comment by addisonamiri** [comment]
It's actually a bug in neovim. The issue is [here](https://github.com/neovim/neovim/issues/2953).
