### ISSUE TITLE
Message in terminal: "Failed to register: Unable to acquire bus name 'org.neovim'"

### ISSUE THREAD

**Issue by candidtim** [fmoralesc/neovim-gnome-terminal-wrapper#4]
On Ubuntu 15.10, when using nvim-wrapper from a terminal, a message gets printed out to the terminal upon a startup:

```
Failed to register: Unable to acquire bus name 'org.neovim'
```

This doesn't seem to impact the behaviour, yet is a little annoying (mostly because I'm left with an empty line instead of a usual shell prompt).

**Comment by fmoralesc** [comment]
I thought I had fixed this :/

**Comment by fmoralesc** [comment]
What gnome-terminal version is this? Are you using the latest version of the wrapper script?

**Comment by candidtim** [comment]
I'm using the latest script from master branch (as of yesterday :) ). gnome-terminal is 3.16.2. I'm not on latest Neovim release yet though, not sure if it is important (my Neovim was assembled

**Comment by candidtim** [comment]
I'm using the latest wrapper script (as of yesterday :) ). gnome-terminal is 3.16.2. I'm not on latest Neovim though yet, not sure if this is important. (I will update it today anyway, will let you know if this changes anything).

(Sorry for close-reopen, hit the wrong button)

**Comment by fmoralesc** [comment]
Might be gnome-terminal version, I'm running 3.18.1. Updating neovim shouldn't change the behavior of the wrapper.

**Comment by fmoralesc** [comment]
Latest version should fix it, thanks to @polazarus

**Comment by candidtim** [comment]
It does, thanks!
