### ISSUE TITLE
gnome-terminal-server not found in Ubuntu

### ISSUE THREAD

**Issue by FvD** [fmoralesc/neovim-gnome-terminal-wrapper#5]
Apparently the files have a different location on Ubuntu. Following the installation instructions gives the following error:

```
nvim-wrapper crashed with FileNotFoundError in _execute_child():
[Errno 2] No such file or directory: '/usr/lib/gnome-terminal/gnome-terminal-server'
```

**Comment by fmoralesc** [comment]
Do you know where it might be? If the gnome-terminal version is too old, it
might not even exist :/

**Comment by FvD** [comment]
I could not find it, and I could not find any reference in the [gnome-terminal man pages](http://manpages.ubuntu.com/manpages/trusty/man1/gnome-terminal.1.html) either. There is a `--disable-factory` flag that appears to do something similar, but I could not get it to work in your script, and apparently it will be [deprecated in future versions](https://bugzilla.gnome.org/show_bug.cgi?id=707899).

I do like the idea of the wrapper you wrote. The closest I can get now on Ubuntu 14.04 LTS is to set the alias:

```
   alias nn='gnome-terminal -x nvim'
```

This opens a new terminal with nvim running. But your wrapper looks nicer.

**Comment by FvD** [comment]
Digging a little bit deeper it does seem to be a gnome-version issue. On Ubuntu 14.04 the gnome-terminal is at version 3.6.2. And the `gnome-terminal-server` is functionality that was added later. The gnome team keeps a ppa up to date for Ubuntu with the latest version ([ppa:gnome3-team](http://askubuntu.com/questions/605986/how-can-i-upgrade-gnome-terminal-on-ubuntu-14-04-lts)), but I would not dare update this as it might affect the stability of my system.

**Comment by fmoralesc** [comment]
Yes, I should mention this dependency on the README.

**Comment by Amdrel** [comment]
I have this same problem in Fedora 22, however there is a workaround. The problem in my case was that  `gnome-terminal-server` was located at `/usr/libexec/gnome-terminal-server` and symlinking it to `/usr/lib/gnome-terminal/gnome-terminal-server` fixed the problem.

**Comment by fmoralesc** [comment]
@Reshurum Well, that workaround shouldn't be necessary anymore, I added some code to "autodetect" the `gnome-terminal-server` path, and to exit early in case it isn't found.

**Comment by Amdrel** [comment]
@fmoralesc Awesome thank you! If only distributions were consistent. :smile:
