### ISSUE TITLE
Window name is "Terminal" 

### ISSUE THREAD

**Issue by llpamies** [fmoralesc/neovim-gnome-terminal-wrapper#7]
Window name is Terminal instead of the preferred "NVim - file" or similar.

![screenshot from 2015-11-17 11-37-34](https://cloud.githubusercontent.com/assets/452871/11222502/9f7f83ba-8d1f-11e5-8b42-57c5ab1cb500.png)

**Comment by fmoralesc** [comment]
Use `set title` within nvim. I might want to set this by default when using the launcher.

**Comment by llpamies** [comment]
Yest that worked, thanks!!

**Comment by thriveth** [comment]
Is it possible to `set title` automatically by default? I would love that.

**Comment by fmoralesc** [comment]
@thriveth If you use an alias, you can append `-c "set alias"` to the wrapper invocation.

**Comment by fmoralesc** [comment]
An update: I finally got around it and added this behavior by default. ;)
